// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package wa_server_templs

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func PageLayout(title *string, content templ.Component) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en-us\" class=\"dark\"><head><meta charset=\"utf-8\"><meta content=\"IE=edge,chrome=1\" http-equiv=\"X-UA-Compatible\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if title != nil {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<title>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(*title)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internals/wa-server-templs/index.templ`, Line: 10, Col: 18}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</title>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<title>DbToolsWebAdmin</title>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<meta content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no\" name=\"viewport\"><script src=\"https://cdn.tailwindcss.com\"></script><script>\n\t\t\ttailwind.config = {\n\t\t\t\tdarkMode: 'class',\n\t\t\t\ttheme: {\n\t\t\t\t\textend: {\n\t\t\t\t\t\tcolors: {\n\t\t\t\t\t\t\t'brand': '#6366f1'\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t</script><link href=\"assets/css/index.css\" rel=\"stylesheet\"></head><body class=\"bg-slate-950 text-slate-100 antialiased\"><main class=\"min-h-screen flex\"><aside class=\"w-72 border-r border-slate-800 bg-slate-900/80 backdrop-blur\"><div class=\"p-6\"><a href=\"/\" class=\"block text-2xl font-semibold text-indigo-300\">DbTools</a><p class=\"mt-1 text-sm text-slate-400\">PLC DB simulator admin</p></div><nav class=\"px-4 pb-6 space-y-2\"><a href=\"/dashboard\" hx-get=\"/dashboard\" data-path=\"/dashboard\" hx-target=\"#main-container\" hx-swap=\"innerHTML\" hx-push-url=\"true\" class=\"nav-link block rounded-lg px-4 py-3 text-sm font-medium transition bg-indigo-500/20 text-indigo-300 ring-1 ring-indigo-500/30\">Dashboard</a> <a href=\"/vars\" hx-get=\"/vars\" data-path=\"/vars\" hx-target=\"#main-container\" hx-swap=\"innerHTML\" hx-push-url=\"true\" class=\"nav-link block rounded-lg px-4 py-3 text-sm font-medium transition text-slate-300 hover:bg-slate-800 hover:text-indigo-300\">Create Vars</a></nav></aside><section id=\"main-container\" class=\"min-h-screen w-full p-8 md:p-10\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = content.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</section></main><script src=\"assets/js/htmx.min.js\"></script><script src=\"assets/js/dist/index.bundle.min.js\"></script><script>\n\t\tconst activeClasses = [\"bg-indigo-500/20\", \"text-indigo-300\", \"ring-1\", \"ring-indigo-500/30\"];\n\t\tconst inactiveClasses = [\"text-slate-300\", \"hover:bg-slate-800\", \"hover:text-indigo-300\"];\n\t\tfunction refreshSidebarState() {\n\t\t\tconst currentPath = window.location.pathname;\n\t\t\tdocument.querySelectorAll(\".nav-link\").forEach((link) => {\n\t\t\t\tconst linkPath = link.getAttribute(\"data-path\");\n\t\t\t\tconst active = linkPath === currentPath || (currentPath === \"/\" && linkPath === \"/dashboard\");\n\t\t\t\tlink.classList.remove(...activeClasses, ...inactiveClasses);\n\t\t\t\tlink.classList.add(...(active ? activeClasses : inactiveClasses));\n\t\t\t});\n\t\t}\n\t\twindow.addEventListener(\"DOMContentLoaded\", refreshSidebarState);\n\t\tdocument.addEventListener(\"htmx:afterOnLoad\", refreshSidebarState);\n\t</script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
